heat_template_version: 2016-10-14
resources:{% for vm in params %} {% set vmindex = loop.index %}
    vdu_{{ vmindex }}:
       type: OS::Nova::Server
       properties: 
        #availability_zone: {{ vm.az }}
          image: {{ vm.image_id }} {% if vm.flavorname %}
          flavor: {get_resource: {{ vm.flavorname }}_type}{% else %}
          flavor: {{ vm.flavor }} {% endif %}{% if vm.cloud_init_file %}
          user_data:
            get_file: ./scripts/{{ vm.cloud_init_file }} {% endif %} 
          networks:
             - port: { get_resource: {{ vm.nic1_name }}_vdu_{{ vmindex }}_port1 }{% if vm.nic2_name %}
             - port: { get_resource: {{ vm.nic2_name }}_vdu_{{ vmindex }}_port2 }{% endif %}{% if vm.nic3_name %}
             - port: { get_resource: {{ vm.nic3_name }}_vdu_{{ vmindex }}_port3 }{% endif %}{% if vm.nic4_name %}
             - port: { get_resource: {{ vm.nic4_name }}_vdu_{{ vmindex }}_port4 }{% endif %}{% if vm.nic5_name %}
             - port: { get_resource: {{ vm.nic5_name }}_vdu_{{ vmindex }}_port5 }{% endif %}{% if vm.nic6_name %}
             - port: { get_resource: {{ vm.nic6_name }}_vdu_{{ vmindex }}_port6 }{% endif %}{% if vm.nic7_name %}
             - port: { get_resource: {{ vm.nic7_name }}_vdu_{{ vmindex }}_port7 }{% endif %}{% if vm.nic8_name %}
             - port: { get_resource: {{ vm.nic8_name }}_vdu_{{ vmindex }}_port8 }{% endif %}{% if vm.nic9_name %}
             - port: { get_resource: {{ vm.nic9_name }}_vdu_{{ vmindex }}_port9 }{% endif %}{% if vm.nic10_name %}
             - port: { get_resource: {{ vm.nic10_name }}_vdu_{{ vmindex }}_port10 }{% endif %}
           #TBD : On each instance consider about 10 nics
    {{ vm.nic1_name }}_vdu_{{ vmindex }}_port1:
         type: OS::Neutron::Port
         properties: {% if vim_params.NewNetworks.get(vm.nic1_name) %}
            network_id: {get_resource: {{ vm.nic1_name }}} {% else %}
            network_id: {{ vm.nic1_name }} {% endif %}
            binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic1_name) %}
            fixed_ips: {% if vm.static_ip_address1 %}
              - ip_address: {{ vm.static_ip_address1 }} {% else %}
              - subnet_id:  { get_resource: {{ vm.nic1_name }}_subnet }{% endif %}{% endif %}
    {% if vm.nic2_name %}
    {{ vm.nic2_name }}_vdu_{{ vmindex }}_port2:
      type: OS::Neutron::Port
      properties: {% if vim_params.NewNetworks.get(vm.nic2_name) %}
         network_id: {get_resource: {{ vm.nic2_name }}} {% else %}
         network_id: {{ vm.nic2_name }} {% endif %}
         binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic2_name) %}
         fixed_ips: {% if vm.static_ip_address2 %}
           - ip_address: {{ vm.static_ip_address2 }} {% else %}
           - subnet_id:  {get_resource: {{ vm.nic2_name }}_subnet }{% endif %}{% endif %}{% endif %}
    {% if vm.nic3_name %}
    {{ vm.nic3_name }}_vdu_{{ vmindex }}_port3:
       type: OS::Neutron::Port
       properties: {% if vim_params.NewNetworks.get(vm.nic3_name) %}
         network_id: {get_resource: {{ vm.nic3_name }} } {% else %}
         network_id: {{ vm.nic3_name }} {% endif %}
         binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic3_name) %}
         fixed_ips: {% if vm.static_ip_address3 %}
            - ip_address: {{ vm.static_ip_address3 }} {% else %}
            - subnet_id: {{ vim_params.NewNetworks.get(vm.nic3_name) }}{% endif %}{% endif %}{% endif %}
    {% if vm.nic4_name %}
    {{ vm.nic4_name }}_vdu_{{ vmindex }}_port4:
       type: OS::Neutron::Port
       properties: {% if vim_params.NewNetworks.get(vm.nic4_name) %}
         network_id: {get_resource: {{ vm.nic4_name }}} {% else %}
         network_id: {{ vm.nic4_name }} {% endif %}
         binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic4_name) %}
         fixed_ips: {% if vm.static_ip_address4 %}
           - ip_address: {{ vm.static_ip_address4 }} {% else %}
           - subnet_id: {{ vim_params.NewNetworks.get(vm.nic4_name) }}{% endif %}{% endif %}{% endif %}
    {% if vm.nic5_name %}
    {{ vm.nic5_name }}_vdu_{{ vmindex }}_port5:
       type: OS::Neutron::Port
       properties: {% if vim_params.NewNetworks.get(vm.nic5_name) %}
         network_id: {get_resource: {{ vm.nic5_name }}} {% else %}
         network_id: {{ vm.nic5_name }} {% endif %}
         binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic5_name) %}
         fixed_ips: {% if vm.static_ip_address5 %}
            - ip_address: {{ vm.static_ip_address5 }} {% else %}
            - subnet_id: {{ vim_params.NewNetworks.get(vm.nic5_name) }}{% endif %}{% endif %}{% endif %}
    {% if vm.nic6_name %}
    {{ vm.nic6_name }}_vdu_{{ vmindex }}_port6:
       type: OS::Neutron::Port
       properties: {% if vim_params.NewNetworks.get(vm.nic6_name) %}
         network_id: { get_resource: {{ vm.nic6_name }} } {% else %}
	 network_id: {{ vm.nic6_name }} {% endif %}
         binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic6_name) %}
         fixed_ips: {% if vm.static_ip_address6 %}
           - ip_address: {{ vm.static_ip_address6 }} {% else %}
           - subnet_id: {{ vim_params.NewNetworks.get(vm.nic6_name) }}{% endif %}{% endif %}{% endif %}
    {% if vm.nic7_name %}
    {{ vm.nic7_name }}_vdu_{{ vmindex }}_port7:
        type: OS::Neutron::Port
        properties: {% if vim_params.NewNetworks.get(vm.nic7_name) %}
           network_id: {get_resource: {{ vm.nic7_name }}} {% else %}
	   network_id: {{ vm.nic7_name }} {% endif %}
           binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic7_name) %}
           fixed_ips: {% if vm.static_ip_address7 %}
             - ip_address: {{ vm.static_ip_address7 }} {% else %}
             - subnet_id: {{ vim_params.NewNetworks.get(vm.nic7_name) }}{% endif %}{% endif %}{% endif %}
    {% if vm.nic8_name %}
    {{ vm.nic8_name }}_vdu_{{ vmindex }}_port8:
        type: OS::Neutron::Port
        properties: {% if vim_params.NewNetworks.get(vm.nic8_name) %}
          network_id: {get_resource: {{ vm.nic8_name }}} {% else %}
          network_id: {{  vm.nic8_name }} {% endif %}
          binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic8_name) %}
          fixed_ips: {% if vm.static_ip_address8 %}
             - ip_address: {{ vm.static_ip_address8 }} {% else %}
             - subnet_id: {{ vim_params.NewNetworks.get(vm.nic8_name) }}{% endif %}{% endif %}{% endif %}
    {% if vm.nic9_name %}
    {{ vm.nic9_name }}_vdu_{{ vmindex }}_port9:
        type: OS::Neutron::Port
        properties: {% if vim_params.NewNetworks.get(vm.nic9_name) %}
           network_id: {get_resource: {{ vm.nic9_name }} } {% else %}
           network_id: {{ vm.nic9_name }} {% endif %}
           binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic9_name) %}
           fixed_ips: {% if vm.static_ip_address9 %}
             - ip_address: {{ vm.static_ip_address9 }} {% else %}
             - subnet_id: {{ vim_params.NewNetworks.get(vm.nic9_name) }}{% endif %}{% endif %}{% endif %} 
    {% if vm.nic10_name %}
    {{ vm.nic10_name }}_vdu_{{ vmindex }}_port10:
        type: OS::Neutron::Port
        properties: {% if vim_params.NewNetworks.get(vm.nic10_name) %}
           network_id: {get_resource: {{ vm.nic10_name }} } {% else %}
           network_id: {{ vm.nic10_name }} {% endif %}
           binding:vnic_type: normal {% if vim_params.NewNetworks.get(vm.nic10_name) %}
           fixed_ips: {% if vm.static_ip_address10 %}
              - ip_address: {{ vm.static_ip_address10 }} {% else %}
              - subnet_id: {{ vim_params.NewNetworks.get(vm.nic10_name) }}{% endif %}{% endif %}{% endif %}
    {% if vm.flavor == 'auto' %}
    {{ vm.flavorname }}_type:
        type: OS::Nova::Flavor
        properties:
           name:  {{ vm.flavorname }}
           ram:  {{ vm.ram }}
           disk: {{ vm.disk }}
           vcpus: {{ vm.cpu }}
           extra_specs: { {% if vm.latency_sensitivity %} cpu_policy: dedicated {% endif %}, {% if vm.memory_reservation %} mem_page_size: Large {% endif %}, {% if vm.numa_affinity %} numa_nodes: {{ vm.number_numa_node }} {% endif %} } {% endif %} {% endfor %}       
    # New Networks to be created
    {% for network in vim_params.NewNetworks %} 
    {{ network }}:
        type: OS::Neutron::Net
        properties:
           name: network_{{ loop.index }}
    {{ network }}_subnet:
        type: OS::Neutron::Subnet
        properties: 
          network_id: { get_resource: {{ network }} }
          cidr: {{ vim_params.NewNetworks.get(network) }}
          ip_version: 4 {% endfor %}

